# Generated by Django 5.1.3 on 2025-08-25 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_court_facilitysignuprequest_sport_userprofile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='sport_text',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='facility',
            name='sport_type',
            field=models.CharField(blank=True, choices=[('tennis', 'Tennis'), ('football', 'Football'), ('basketball', 'Basketball'), ('swimming', 'Swimming'), ('gym', 'Gym')], help_text='Legacy field for old facilities. New entries should use sport_text.', max_length=30, null=True),
        ),
    ]
