# Generated by Django 5.1.3 on 2025-08-25 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_facility_sport_text_alter_facility_sport_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='sport_text',
            field=models.CharField(blank=True, db_index=True, max_length=60),
        ),
    ]
