# Generated by Django 5.1.3 on 2025-08-25 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_alter_facility_sport_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='blackout',
            name='note',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
