# Generated by Django 5.1.3 on 2025-08-25 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0005_blackout_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='sport_type',
            field=models.CharField(blank=True, choices=[('tennis', 'Tennis'), ('football', 'Football'), ('basketball', 'Basketball'), ('swimming', 'Swimming'), ('gym', 'Gym')], max_length=30, null=True),
        ),
    ]
